name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 'net6.0' # Adjust the version as needed

    - name: Build .NET Core Project
      run: dotnet build WebApiExample/WebApiExample/WebApiCrud.csproj --configuration Release

    - name: Deploy to Elastic Beanstalk
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws elasticbeanstalk create-application-version \
          --application-name ${{ secrets.AWS_ELASTIC_BEANSTALK_APP_NAME }} \
          --version-label $GITHUB_SHA \
          --source-bundle S3Bucket="elasticbeanstalk-$AWS_REGION",S3Key=$GITHUB_SHA.zip
        aws elasticbeanstalk update-environment \
          --application-name ${{ secrets.AWS_ELASTIC_BEANSTALK_APP_NAME }} \
          --environment-name ${{ secrets.AWS_ELASTIC_BEANSTALK_ENV_NAME }} \
          --version-label $GITHUB_SHA
      env:
        DOTNET_ROOT: ${{ secrets.DOTNET_ROOT }}
